#include<iostream.h>
#include<conio.h>
#include<stdio.h>

void main()
{
clrscr();
class tickbooth
{
  int people;
  int amount;
  public;
  void tickbooth();
  void tickholder();
  void passholder();
  void displaytotal();
}//end of class declaration

tickbooth::tickbooth()
{
 people=0;
 amount=0;
 }
tickbooth::tickholder()
{
 people+=x;
 amount+=x;
 }
tickbooth::passholder(int x)
{
 poeple+=x;
 }

void tickbooth::displaytotal()
{
cout<<"no of visiter "<<people<<"\n";
cout<<"amount collescted"<<amount<<"\n";
}
void tickbooth::ticksold()
{
cout<<"no of tickets sold are"<<(int)amount/2;
}


void main;
{
clrscr();
tickbooth,obj;
int opt,x

cout<<"options";




